# Generated by Django 3.1.7 on 2021-04-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Uname', models.CharField(max_length=30, unique=True)),
                ('Profile_pic', models.ImageField(default='', upload_to='user_img')),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('Aadhar', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=255)),
                ('Work_status', models.CharField(max_length=255)),
                ('Work_desc', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=15)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cont_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('email_addr', models.CharField(max_length=100)),
                ('ph_no', models.CharField(max_length=12)),
                ('Content', models.TextField()),
                ('timeStamp1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=30)),
                ('User_Email', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Owner', models.CharField(max_length=40)),
                ('Product_ID', models.IntegerField()),
                ('Auction_date', models.DateField()),
                ('Auction_time', models.TimeField()),
                ('Initial_Bid_Amt', models.IntegerField()),
                ('PassCode', models.CharField(max_length=5)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_owner', models.CharField(max_length=40)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_bought_date', models.DateField()),
                ('Starting_Bid', models.IntegerField()),
                ('Auction_pref_date', models.DateField()),
                ('Auction_pref_time', models.TimeField()),
                ('AuctionEnded', models.CharField(default='No', max_length=3)),
                ('Product_desc', models.CharField(max_length=255)),
                ('Product_img', models.ImageField(upload_to='auction_prod')),
                ('Auction_Passcode', models.CharField(max_length=5)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('Prod_Owner_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.client')),
            ],
        ),
    ]
