# Generated by Django 3.1.7 on 2021-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AucPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='OwnerID',
        ),
        migrations.AddField(
            model_name='auction',
            name='OwnerName',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
